spring.application.name=FitnessProject

# SQL Server connection (SQL login)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FitnessdDB;encrypt=true;trustServerCertificate=true
#i seriously mispelled the db when i was creating in ssms so now I have to deal with this being a mistake until I fix it
# below is sql server login infor for connecting. Supposed to be able to use from laptop as well
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect